<a href="https://colab.research.google.com/github/h220101/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [8]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)

## CSV 형식 저장
df.to_csv('student_analysis.csv', encoding='utf-8', index=False)

## 5-2 JSON 형식 저장

In [14]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output.json', mode='w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)

## DataFrame을 이용한 저장
df = pd.DataFrame([data])
# df.to_json('output_df.json', orient='records', indent=4, force_ascii=False)
df.to_json('output_df.json', orient='columns', indent=4, force_ascii=False)

## 5-3 Pandas Dataframe 데이터 추출

In [22]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
df

## DataFrame 인덱스 출력
print(df.index)

## DataFrame 컬럼 출력
print(df.columns)

## DataFrame 행 출력
print(df.values.tolist()) #파이썬 리스트 형태
print(df.values) #NumPy array 형태

## DataFrame 값 출력
print(df.values.flatten()) #구조 없이 일렬로 나열

RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
[['김철수' 1 4.2 '컴퓨터학' '프로그래밍']
 ['이영희' 2 3.8 '경영학' '독서토론']
 ['박민수' 3 4.5 '농학' '로봇공학']
 ['최지훈' 4 3.9 '교육학' '봉사활동']
 ['정소희' 2 3.5 '영어영문학' '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [33]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
df2 = pd.read_csv('students.csv')
df3 = pd.read_json('students.json')

## 세가지 방법 결과 비교
print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [35]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df1 = pd.DataFrame(data)

## CSV, JSON 형식으로 저장
df.to_csv('students_scores.csv')
df.to_json('students_scores.json')

## HTML 형식으로 저장
html_table = df.to_html()
# print(html_table)
with open('students_scores.html', 'w') as f:
    f.write(html_table)

## 5-6 실습 시나리오

## 데이터 수집

In [79]:
##기상청 태풍 api 대체 실습 (csv 텍스트만 제공 -> json 리스트로 변환)
import pandas as pd
from io import StringIO
import requests

api_key = "hiiFdpmxQSyohXaZsQEsgg"

url = "https://apihub.kma.go.kr/api/typ01/url/typ_lst.php"
params = {
    "YY": 2012,
    "disp": 1,   # 쉼표 구분
    "help": 0,   # 헤더 포함
    "authKey": api_key
}

response = requests.get(url, params=params)

# CSV 텍스트 -> pandas DataFrame으로 변환
csv_data = StringIO(response.text)
df = pd.read_csv(csv_data, sep=",", engine="python", comment="#", on_bad_lines="skip")

# DataFrame -> JSON 리스트 형태로 변환
json_list = df.to_dict(orient="records")

print(json_list)

[{'2012': 2012, '1': 2, '2': 2, '4': 4, '201203290000': 201205220000, '201204020000': 201205280300, '파카르': '상우', 'PAKHAR': 'SANVU', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제2호 태풍[상우(SANVU)]은 마카오에서 제출한 이름으로 산호를 의미함.', '=': '='}, {'2012': 2012, '1': 3, '2': 2, '4': 4, '201203290000': 201206010600, '201204020000': 201206060600, '파카르': '마와르', 'PAKHAR': 'MAWAR', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제3호 태풍[마와르(MAWAR)]은 말레이시아에서 제출한 이름으로 장미를 의미함.', '=': '='}, {'2012': 2012, '1': 4, '2': 2, '4': 4, '201203290000': 201206120600, '201204020000': 201206200000, '파카르': '구촐', 'PAKHAR': 'GUCHOL', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제4호 태풍[구촐(GUCHOL)]은 미크로네시아에서 제출한 이름으로 향신료를 의미함.', '=': '='}, {'2012': 2012, '1': 5, '2': 2, '4': 4, '201203290000': 201206171800, '201204020000': 201206202100, '파카르': '탈림', 'PAKHAR': 'TALIM', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제5호 태풍[탈림(TALIM)]은 필리핀에서 제출한 이름으로 가장자리를 의미함.', '=': '='}, {'2012': 2012, '1': 6, '2': 2, '4': 4, '201203290000': 201206261200, '201204020000': 201206300000, '파카르': '독수리', 'PAKHAR': 'DOKSURI', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제6호 태풍[독수리(DOKSURI)]은 한국에서 제출한 이름임.', '=': '='}, {'2012': 2012, '1': 7, '2': 2, '4': 1, '201203290000': 201207160600, '201204020000': 201207190300, '파카르': '카눈', 'PAKHAR': 'KHANUN', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제7호 태풍[카눈(KHANUN)]은 태국에서 제출한 이름으로 열대과일의 하나임.', '=': '='}, {'2012': 2012, '1': 8, '2': 2, '4': 4, '201203290000': 201207211200, '201204020000': 201207241800, '파카르': '비센티', 'PAKHAR': 'VICENTE', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제8호 태풍[비센티(VICENTE)]은 미국에서 제출한 이름으로 남자 이름임.', '=': '='}, {'2012': 2012, '1': 9, '2': 2, '4': 4, '201203290000': 201207280000, '201204020000': 201208030600, '파카르': '사올라', 'PAKHAR': 'SAOLA', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제9호 태풍[사올라(SAOLA)]은 베트남에서 제출한 이름으로 동물의 한 종류임.', '=': '='}, {'2012': 2012, '1': 10, '2': 2, '4': 2, '201203290000': 201207281200, '201204020000': 201208030600, '파카르': '담레이', 'PAKHAR': 'DAMREY', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제10호 태풍[담레이(DAMREY)]은 캄보디아에서 제출한 이름으로 코끼리를 의미함.', '=': '='}, {'2012': 2012, '1': 11, '2': 2, '4': 4, '201203290000': 201208030000, '201204020000': 201208091200, '파카르': '하이쿠이', 'PAKHAR': 'HAIKUI', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제11호 태풍[하이쿠이(HAIKUI)]은 중국에서 제출한 이름으로 말미잘을 의미함.', '=': '='}, {'2012': 2012, '1': 12, '2': 2, '4': 4, '201203290000': 201208080000, '201204020000': 201208100000, '파카르': '기러기', 'PAKHAR': 'KIROGI', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제12호 태풍[기러기(KIROGI)]은 북한에서 제출한 이름임.', '=': '='}, {'2012': 2012, '1': 13, '2': 2, '4': 4, '201203290000': 201208130000, '201204020000': 201208180600, '파카르': '카이탁', 'PAKHAR': 'KAI-TAK', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제13호 태풍[카이탁(KAI-TAK)]은 홍콩에서 제출한 이름으로 옛 공항의 이름임.', '=': '='}, {'2012': 2012, '1': 14, '2': 2, '4': 1, '201203290000': 201208190000, '201204020000': 201208301500, '파카르': '덴빈', 'PAKHAR': 'TEMBIN', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제14호 태풍[덴빈(TEMBIN)]은 일본에서 제출한 이름으로 천칭자리(별자리)를 의미함.', '=': '='}, {'2012': 2012, '1': 15, '2': 2, '4': 2, '201203290000': 201208200600, '201204020000': 201208282100, '파카르': '볼라벤', 'PAKHAR': 'BOLAVEN', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제15호 태풍[볼라벤(BOLAVEN)]은 라오스에서 제출한 이름으로 고원의 이름임.', '=': '='}, {'2012': 2012, '1': 16, '2': 2, '4': 1, '201203290000': 201209110000, '201204020000': 201209180000, '파카르': '산바', 'PAKHAR': 'SANBA', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제16호 태풍[산바(SANBA)]은 마카오에서 제출한 이름으로 지명의 이름임.', '=': '='}, {'2012': 2012, '1': 17, '2': 2, '4': 4, '201203290000': 201209201800, '201204020000': 201210010600, '파카르': '즐라왓', 'PAKHAR': 'JELAWAT', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제17호 태풍[즐라왓(JELAWAT)]은 말레이시아에서 제출한 이름으로 잉어과의 민물고기임.', '=': '='}, {'2012': 2012, '1': 18, '2': 2, '4': 4, '201203290000': 201209241200, '201204020000': 201209300000, '파카르': '에위니아', 'PAKHAR': 'EWINIAR', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제18호 태풍[에위니아(EWINIAR)]은 미크로네시아에서 제출한 이름으로 폭풍의 신을 의미함.', '=': '='}, {'2012': 2012, '1': 19, '2': 2, '4': 4, '201203290000': 201210010600, '201204020000': 201210040600, '파카르': '말릭시', 'PAKHAR': 'MALIKSI', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제19호 태풍[말릭시(MALIKSI)]은 필리핀에서 제출한 이름으로 빠름을 의미함.', '=': '='}, {'2012': 2012, '1': 20, '2': 2, '4': 4, '201203290000': 201210011200, '201204020000': 201210061200, '파카르': '개미', 'PAKHAR': 'GAEMI', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제20호 태풍[개미(GAEMI)]은 한국에서 제출한 이름임.', '=': '='}, {'2012': 2012, '1': 21, '2': 2, '4': 4, '201203290000': 201210071200, '201204020000': 201210190600, '파카르': '쁘라삐룬', 'PAKHAR': 'PRAPIROON', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제21호 태풍[쁘라삐룬(PRAPIROON)]은 태국에서 제출한 이름으로 비의 신을 의미함.', '=': '='}, {'2012': 2012, '1': 22, '2': 2, '4': 4, '201203290000': 201210141200, '201204020000': 201210181800, '파카르': '마리아', 'PAKHAR': 'MARIA', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제22호 태풍[마리아(MARIA)]은 미국에서 제출한 이름으로 여자 이름임.', '=': '='}, {'2012': 2012, '1': 23, '2': 2, '4': 4, '201203290000': 201210231800, '201204020000': 201210290600, '파카르': '손띤', 'PAKHAR': 'SON-TINH', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제23호 태풍[손띤(SON-TINH)]은 베트남에서 제출한 이름으로 신화속의 산신 이름임.', '=': '='}, {'2012': 2012, '1': 24, '2': 2, '4': 4, '201203290000': 201211261800, '201204020000': 201212090600, '파카르': '보파', 'PAKHAR': 'BOPHA', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제24호 태풍[보파(BOPHA)]는 캄보디아에서 제출한 이름으로 꽃을 의미함.', '=': '='}, {'2012': 2012, '1': 25, '2': 2, '4': 4, '201203290000': 201212250000, '201204020000': 201212271200, '파카르': '우쿵', 'PAKHAR': 'WUKONG', '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제25호 태풍[우쿵(WUKONG)]은 중국에서 제출한 이름으로 원숭이의 왕을 의미함.', '=': '='}]

In [78]:
json_list

[{'2012': 2012,
  '1': 2,
  '2': 2,
  '4': 4,
  '201203290000': 201205220000,
  '201204020000': 201205280300,
  '파카르': '상우',
  'PAKHAR': 'SANVU',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제2호 태풍[상우(SANVU)]은 마카오에서 제출한 이름으로 산호를 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 3,
  '2': 2,
  '4': 4,
  '201203290000': 201206010600,
  '201204020000': 201206060600,
  '파카르': '마와르',
  'PAKHAR': 'MAWAR',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제3호 태풍[마와르(MAWAR)]은 말레이시아에서 제출한 이름으로 장미를 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 4,
  '2': 2,
  '4': 4,
  '201203290000': 201206120600,
  '201204020000': 201206200000,
  '파카르': '구촐',
  'PAKHAR': 'GUCHOL',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제4호 태풍[구촐(GUCHOL)]은 미크로네시아에서 제출한 이름으로 향신료를 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 5,
  '2': 2,
  '4': 4,
  '201203290000': 201206171800,
  '201204020000': 201206202100,
  '파카르': '탈림',
  'PAKHAR': 'TALIM',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제5호 태풍[탈림(TALIM)]은 필리핀에서 제출한 이름으로 가장자리를 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 6,
  '2': 2,
  '4': 4,
  '201203290000': 201206261200,
  '201204020000': 201206300000,
  '파카르': '독수리',
  'PAKHAR': 'DOKSURI',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제6호 태풍[독수리(DOKSURI)]은 한국에서 제출한 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 7,
  '2': 2,
  '4': 1,
  '201203290000': 201207160600,
  '201204020000': 201207190300,
  '파카르': '카눈',
  'PAKHAR': 'KHANUN',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제7호 태풍[카눈(KHANUN)]은 태국에서 제출한 이름으로 열대과일의 하나임.',
  '=': '='},
 {'2012': 2012,
  '1': 8,
  '2': 2,
  '4': 4,
  '201203290000': 201207211200,
  '201204020000': 201207241800,
  '파카르': '비센티',
  'PAKHAR': 'VICENTE',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제8호 태풍[비센티(VICENTE)]은 미국에서 제출한 이름으로 남자 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 9,
  '2': 2,
  '4': 4,
  '201203290000': 201207280000,
  '201204020000': 201208030600,
  '파카르': '사올라',
  'PAKHAR': 'SAOLA',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제9호 태풍[사올라(SAOLA)]은 베트남에서 제출한 이름으로 동물의 한 종류임.',
  '=': '='},
 {'2012': 2012,
  '1': 10,
  '2': 2,
  '4': 2,
  '201203290000': 201207281200,
  '201204020000': 201208030600,
  '파카르': '담레이',
  'PAKHAR': 'DAMREY',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제10호 태풍[담레이(DAMREY)]은 캄보디아에서 제출한 이름으로 코끼리를 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 11,
  '2': 2,
  '4': 4,
  '201203290000': 201208030000,
  '201204020000': 201208091200,
  '파카르': '하이쿠이',
  'PAKHAR': 'HAIKUI',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제11호 태풍[하이쿠이(HAIKUI)]은 중국에서 제출한 이름으로 말미잘을 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 12,
  '2': 2,
  '4': 4,
  '201203290000': 201208080000,
  '201204020000': 201208100000,
  '파카르': '기러기',
  'PAKHAR': 'KIROGI',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제12호 태풍[기러기(KIROGI)]은 북한에서 제출한 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 13,
  '2': 2,
  '4': 4,
  '201203290000': 201208130000,
  '201204020000': 201208180600,
  '파카르': '카이탁',
  'PAKHAR': 'KAI-TAK',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제13호 태풍[카이탁(KAI-TAK)]은 홍콩에서 제출한 이름으로 옛 공항의 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 14,
  '2': 2,
  '4': 1,
  '201203290000': 201208190000,
  '201204020000': 201208301500,
  '파카르': '덴빈',
  'PAKHAR': 'TEMBIN',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제14호 태풍[덴빈(TEMBIN)]은 일본에서 제출한 이름으로 천칭자리(별자리)를 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 15,
  '2': 2,
  '4': 2,
  '201203290000': 201208200600,
  '201204020000': 201208282100,
  '파카르': '볼라벤',
  'PAKHAR': 'BOLAVEN',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제15호 태풍[볼라벤(BOLAVEN)]은 라오스에서 제출한 이름으로 고원의 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 16,
  '2': 2,
  '4': 1,
  '201203290000': 201209110000,
  '201204020000': 201209180000,
  '파카르': '산바',
  'PAKHAR': 'SANBA',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제16호 태풍[산바(SANBA)]은 마카오에서 제출한 이름으로 지명의 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 17,
  '2': 2,
  '4': 4,
  '201203290000': 201209201800,
  '201204020000': 201210010600,
  '파카르': '즐라왓',
  'PAKHAR': 'JELAWAT',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제17호 태풍[즐라왓(JELAWAT)]은 말레이시아에서 제출한 이름으로 잉어과의 민물고기임.',
  '=': '='},
 {'2012': 2012,
  '1': 18,
  '2': 2,
  '4': 4,
  '201203290000': 201209241200,
  '201204020000': 201209300000,
  '파카르': '에위니아',
  'PAKHAR': 'EWINIAR',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제18호 태풍[에위니아(EWINIAR)]은 미크로네시아에서 제출한 이름으로 폭풍의 신을 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 19,
  '2': 2,
  '4': 4,
  '201203290000': 201210010600,
  '201204020000': 201210040600,
  '파카르': '말릭시',
  'PAKHAR': 'MALIKSI',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제19호 태풍[말릭시(MALIKSI)]은 필리핀에서 제출한 이름으로 빠름을 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 20,
  '2': 2,
  '4': 4,
  '201203290000': 201210011200,
  '201204020000': 201210061200,
  '파카르': '개미',
  'PAKHAR': 'GAEMI',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제20호 태풍[개미(GAEMI)]은 한국에서 제출한 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 21,
  '2': 2,
  '4': 4,
  '201203290000': 201210071200,
  '201204020000': 201210190600,
  '파카르': '쁘라삐룬',
  'PAKHAR': 'PRAPIROON',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제21호 태풍[쁘라삐룬(PRAPIROON)]은 태국에서 제출한 이름으로 비의 신을 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 22,
  '2': 2,
  '4': 4,
  '201203290000': 201210141200,
  '201204020000': 201210181800,
  '파카르': '마리아',
  'PAKHAR': 'MARIA',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제22호 태풍[마리아(MARIA)]은 미국에서 제출한 이름으로 여자 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 23,
  '2': 2,
  '4': 4,
  '201203290000': 201210231800,
  '201204020000': 201210290600,
  '파카르': '손띤',
  'PAKHAR': 'SON-TINH',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제23호 태풍[손띤(SON-TINH)]은 베트남에서 제출한 이름으로 신화속의 산신 이름임.',
  '=': '='},
 {'2012': 2012,
  '1': 24,
  '2': 2,
  '4': 4,
  '201203290000': 201211261800,
  '201204020000': 201212090600,
  '파카르': '보파',
  'PAKHAR': 'BOPHA',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제24호 태풍[보파(BOPHA)]는 캄보디아에서 제출한 이름으로 꽃을 의미함.',
  '=': '='},
 {'2012': 2012,
  '1': 25,
  '2': 2,
  '4': 4,
  '201203290000': 201212250000,
  '201204020000': 201212271200,
  '파카르': '우쿵',
  'PAKHAR': 'WUKONG',
  '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.': '제25호 태풍[우쿵(WUKONG)]은 중국에서 제출한 이름으로 원숭이의 왕을 의미함.',
  '=': '='}]

## 데이터 프레임 생성

In [117]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기
# data = response.json()['response']['body']['items']
# print(type(data))
# print(len(data))
# print(data[0])
# df = pd.DataFrame(data)

## 기상청 태풍 api 대체 실습
data = json_list
print(df.head())

print(type(data))

print(len(data))

df = pd.DataFrame(data)

print(df.columns)

df.columns = [
    'YY', 'SEQ', 'NOW', 'EFF', 'TM_ST', 'TM_ED',
    'TYP_NAME', 'TYP_EN', 'REM', 'ETC'
]

print(df['TYP_NAME'])

df.head()

     YY  SEQ  NOW  EFF         TM_ST         TM_ED TYP_NAME   TYP_EN  \
0  2012    2    2    4  201205220000  201205280300       상우    SANVU
1  2012    3    2    4  201206010600  201206060600      마와르    MAWAR
2  2012    4    2    4  201206120600  201206200000       구촐   GUCHOL
3  2012    5    2    4  201206171800  201206202100       탈림    TALIM
4  2012    6    2    4  201206261200  201206300000      독수리  DOKSURI

                                               REM ETC
0       제2호 태풍[상우(SANVU)]은 마카오에서 제출한 이름으로 산호를 의미함.   =
1    제3호 태풍[마와르(MAWAR)]은 말레이시아에서 제출한 이름으로 장미를 의미함.   =
2  제4호 태풍[구촐(GUCHOL)]은 미크로네시아에서 제출한 이름으로 향신료를 의미함.   =
3     제5호 태풍[탈림(TALIM)]은 필리핀에서 제출한 이름으로 가장자리를 의미함.   =
4              제6호 태풍[독수리(DOKSURI)]은 한국에서 제출한 이름임.   =
<class 'list'>
24
Index(['2012', '1', '2', '4', '201203290000', '201204020000', '파카르', 'PAKHAR',
       '제1호 태풍[파카르(PAKHAR)]은 라오스에서 제출한 이름으로 메콩강에 서식하는 민물고기임.', '='],
      dtype='object')
0       상우
1      마와르
2       구촐
3       탈림
4      독수리
5       카눈
6      비센티
7      사올라
8      담레이
9     하이쿠이
10     기러기
11     카이탁
12      덴빈
13     볼라벤
14      산바
15     즐라왓
16    에위니아
17     말릭시
18      개미
19    쁘라삐룬
20     마리아
21      손띤
22      보파
23      우쿵
Name: TYP_NAME, dtype: object

,YY,SEQ,NOW,EFF,TM_ST,TM_ED,TYP_NAME,TYP_EN,REM,ETC
0,2012,2,2,4,201205220000,201205280300,상우,SANVU,제2호 태풍[상우(SANVU)]은 마카오에서 제출한 이름으로 산호를 의미함.,=
1,2012,3,2,4,201206010600,201206060600,마와르,MAWAR,제3호 태풍[마와르(MAWAR)]은 말레이시아에서 제출한 이름으로 장미를 의미함.,=
2,2012,4,2,4,201206120600,201206200000,구촐,GUCHOL,제4호 태풍[구촐(GUCHOL)]은 미크로네시아에서 제출한 이름으로 향신료를 의미함.,=
3,2012,5,2,4,201206171800,201206202100,탈림,TALIM,제5호 태풍[탈림(TALIM)]은 필리핀에서 제출한 이름으로 가장자리를 의미함.,=
4,2012,6,2,4,201206261200,201206300000,독수리,DOKSURI,제6호 태풍[독수리(DOKSURI)]은 한국에서 제출한 이름임.,=

## 다양항 형식으로 데이터 저장

In [121]:
## csv 형식 데이터 저장
df.to_csv('typhoon.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('typhoon.json', orient='records', indent=4, force_ascii=False)

## EXCEL 형식 데이터 저장
df.to_excel('typhoon.xlsx', index=False)

## HTML 형식 데이터 저장
df.to_html('typhoon.html')